// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, owner_id, name) VALUES ($1,$2,$3)
`

type InsertAccountParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount, arg.ID, arg.OwnerID, arg.Name)
	return err
}
