// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getAuditEventsByRequestID = `-- name: GetAuditEventsByRequestID :many
SELECT id, request_id, user_id, session_id, resource, resource_id, action, result, timestamp, user_agent, client_ip
FROM audit_events
WHERE request_id = $1
ORDER BY timestamp DESC
`

func (q *Queries) GetAuditEventsByRequestID(ctx context.Context, requestID string) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, getAuditEventsByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.UserID,
			&i.SessionID,
			&i.Resource,
			&i.ResourceID,
			&i.Action,
			&i.Result,
			&i.Timestamp,
			&i.UserAgent,
			&i.ClientIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (id, request_id, user_id, session_id, resource, resource_id, action, result, timestamp, user_agent, client_ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertAuditEventParams struct {
	ID         uuid.UUID      `json:"id"`
	RequestID  string         `json:"request_id"`
	UserID     uuid.NullUUID  `json:"user_id"`
	SessionID  uuid.NullUUID  `json:"session_id"`
	Resource   string         `json:"resource"`
	ResourceID sql.NullString `json:"resource_id"`
	Action     string         `json:"action"`
	Result     AuditResult    `json:"result"`
	Timestamp  time.Time      `json:"timestamp"`
	UserAgent  sql.NullString `json:"user_agent"`
	ClientIp   pqtype.Inet    `json:"client_ip"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.ID,
		arg.RequestID,
		arg.UserID,
		arg.SessionID,
		arg.Resource,
		arg.ResourceID,
		arg.Action,
		arg.Result,
		arg.Timestamp,
		arg.UserAgent,
		arg.ClientIp,
	)
	return err
}
