// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertBudget = `-- name: InsertBudget :exec
INSERT INTO budgets (id, owner_id, amount, name) VALUES ($1,$2,$3,$4)
`

type InsertBudgetParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
	Amount  string    `json:"amount"`
	Name    string    `json:"name"`
}

func (q *Queries) InsertBudget(ctx context.Context, arg InsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, insertBudget,
		arg.ID,
		arg.OwnerID,
		arg.Amount,
		arg.Name,
	)
	return err
}
