// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_events.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const fetchPendingDomainEvents = `-- name: FetchPendingDomainEvents :many
SELECT id, event_type, aggregate_id, aggregate_type, event_data, timestamp, processing_status, retry_count
FROM domain_events
WHERE processing_status = 'pending'
ORDER BY timestamp ASC
LIMIT $1
`

type FetchPendingDomainEventsRow struct {
	ID               uuid.UUID        `json:"id"`
	EventType        DomainEventType  `json:"event_type"`
	AggregateID      string           `json:"aggregate_id"`
	AggregateType    string           `json:"aggregate_type"`
	EventData        json.RawMessage  `json:"event_data"`
	Timestamp        time.Time        `json:"timestamp"`
	ProcessingStatus ProcessingStatus `json:"processing_status"`
	RetryCount       int32            `json:"retry_count"`
}

func (q *Queries) FetchPendingDomainEvents(ctx context.Context, limit int32) ([]FetchPendingDomainEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchPendingDomainEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPendingDomainEventsRow
	for rows.Next() {
		var i FetchPendingDomainEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventData,
			&i.Timestamp,
			&i.ProcessingStatus,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDomainEvent = `-- name: InsertDomainEvent :exec
INSERT INTO domain_events (id, event_type, aggregate_id, aggregate_type, event_data, timestamp, processing_status, retry_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertDomainEventParams struct {
	ID               uuid.UUID        `json:"id"`
	EventType        DomainEventType  `json:"event_type"`
	AggregateID      string           `json:"aggregate_id"`
	AggregateType    string           `json:"aggregate_type"`
	EventData        json.RawMessage  `json:"event_data"`
	Timestamp        time.Time        `json:"timestamp"`
	ProcessingStatus ProcessingStatus `json:"processing_status"`
	RetryCount       int32            `json:"retry_count"`
}

func (q *Queries) InsertDomainEvent(ctx context.Context, arg InsertDomainEventParams) error {
	_, err := q.db.ExecContext(ctx, insertDomainEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventData,
		arg.Timestamp,
		arg.ProcessingStatus,
		arg.RetryCount,
	)
	return err
}

const markDomainEventProcessed = `-- name: MarkDomainEventProcessed :exec
UPDATE domain_events SET processing_status = 'processed', processed_at = NOW() WHERE id = $1
`

func (q *Queries) MarkDomainEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markDomainEventProcessed, id)
	return err
}
