// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditResult string

const (
	AuditResultSuccess AuditResult = "success"
	AuditResultFailure AuditResult = "failure"
)

func (e *AuditResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditResult(s)
	case string:
		*e = AuditResult(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditResult: %T", src)
	}
	return nil
}

type NullAuditResult struct {
	AuditResult AuditResult `json:"audit_result"`
	Valid       bool        `json:"valid"` // Valid is true if AuditResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditResult) Scan(value interface{}) error {
	if value == nil {
		ns.AuditResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditResult), nil
}

type DomainEventType string

const (
	DomainEventTypeUSERREGISTERED     DomainEventType = "USER_REGISTERED"
	DomainEventTypeUSERLOGGEDIN       DomainEventType = "USER_LOGGED_IN"
	DomainEventTypeUSERLOGGEDOUT      DomainEventType = "USER_LOGGED_OUT"
	DomainEventTypeACCOUNTCREATED     DomainEventType = "ACCOUNT_CREATED"
	DomainEventTypeTRANSACTIONCREATED DomainEventType = "TRANSACTION_CREATED"
	DomainEventTypeBUDGETCREATED      DomainEventType = "BUDGET_CREATED"
)

func (e *DomainEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DomainEventType(s)
	case string:
		*e = DomainEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for DomainEventType: %T", src)
	}
	return nil
}

type NullDomainEventType struct {
	DomainEventType DomainEventType `json:"domain_event_type"`
	Valid           bool            `json:"valid"` // Valid is true if DomainEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDomainEventType) Scan(value interface{}) error {
	if value == nil {
		ns.DomainEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DomainEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDomainEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DomainEventType), nil
}

type ProcessingStatus string

const (
	ProcessingStatusPending   ProcessingStatus = "pending"
	ProcessingStatusProcessed ProcessingStatus = "processed"
	ProcessingStatusFailed    ProcessingStatus = "failed"
)

func (e *ProcessingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessingStatus(s)
	case string:
		*e = ProcessingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessingStatus: %T", src)
	}
	return nil
}

type NullProcessingStatus struct {
	ProcessingStatus ProcessingStatus `json:"processing_status"`
	Valid            bool             `json:"valid"` // Valid is true if ProcessingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessingStatus), nil
}

type SessionStatus string

const (
	SessionStatusActive  SessionStatus = "active"
	SessionStatusExpired SessionStatus = "expired"
	SessionStatusRevoked SessionStatus = "revoked"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type Account struct {
	ID        uuid.UUID `json:"id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type AuditEvent struct {
	ID         uuid.UUID      `json:"id"`
	RequestID  string         `json:"request_id"`
	UserID     uuid.NullUUID  `json:"user_id"`
	SessionID  uuid.NullUUID  `json:"session_id"`
	Resource   string         `json:"resource"`
	ResourceID sql.NullString `json:"resource_id"`
	Action     string         `json:"action"`
	Result     AuditResult    `json:"result"`
	Timestamp  time.Time      `json:"timestamp"`
	UserAgent  sql.NullString `json:"user_agent"`
	ClientIp   pqtype.Inet    `json:"client_ip"`
}

type Budget struct {
	ID        uuid.UUID `json:"id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	Amount    string    `json:"amount"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type DomainEvent struct {
	ID               uuid.UUID        `json:"id"`
	EventType        DomainEventType  `json:"event_type"`
	AggregateID      string           `json:"aggregate_id"`
	AggregateType    string           `json:"aggregate_type"`
	EventData        json.RawMessage  `json:"event_data"`
	Timestamp        time.Time        `json:"timestamp"`
	ProcessingStatus ProcessingStatus `json:"processing_status"`
	RetryCount       int32            `json:"retry_count"`
	ProcessedAt      sql.NullTime     `json:"processed_at"`
	ErrorMessage     sql.NullString   `json:"error_message"`
}

type Session struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	CreatedAt      time.Time      `json:"created_at"`
	LastActivityAt time.Time      `json:"last_activity_at"`
	ExpiresAt      time.Time      `json:"expires_at"`
	RevokedAt      sql.NullTime   `json:"revoked_at"`
	UserAgent      sql.NullString `json:"user_agent"`
	IpAddress      pqtype.Inet    `json:"ip_address"`
	Status         SessionStatus  `json:"status"`
}

type Transaction struct {
	ID        uuid.UUID      `json:"id"`
	AccountID uuid.UUID      `json:"account_id"`
	Amount    string         `json:"amount"`
	Memo      sql.NullString `json:"memo"`
	CreatedAt time.Time      `json:"created_at"`
}

type TransactionalOutbox struct {
	ID               uuid.UUID        `json:"id"`
	DomainEventID    uuid.UUID        `json:"domain_event_id"`
	EventType        string           `json:"event_type"`
	Payload          json.RawMessage  `json:"payload"`
	CreatedAt        time.Time        `json:"created_at"`
	ProcessingStatus ProcessingStatus `json:"processing_status"`
	RetryCount       int32            `json:"retry_count"`
	ProcessedAt      sql.NullTime     `json:"processed_at"`
	LastRetryAt      sql.NullTime     `json:"last_retry_at"`
	LastError        sql.NullString   `json:"last_error"`
	ErrorMessage     sql.NullString   `json:"error_message"`
}

type User struct {
	UserID       uuid.UUID `json:"user_id"`
	FullName     string    `json:"full_name"`
	DateOfBirth  time.Time `json:"date_of_birth"`
	MobileNumber string    `json:"mobile_number"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
