// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckMobileNumberExists(ctx context.Context, mobileNumber string) (bool, error)
	CheckUsernameExists(ctx context.Context, username string) (bool, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error
	FetchPendingDomainEvents(ctx context.Context, limit int32) ([]FetchPendingDomainEventsRow, error)
	FetchPendingOutbox(ctx context.Context, limit int32) ([]FetchPendingOutboxRow, error)
	GetAuditEventsByRequestID(ctx context.Context, requestID string) ([]AuditEvent, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, userID uuid.UUID) (GetUserByIDRow, error)
	GetUserByMobileNumber(ctx context.Context, mobileNumber string) (GetUserByMobileNumberRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	IncrementOutboxRetry(ctx context.Context, id uuid.UUID) error
	InsertAccount(ctx context.Context, arg InsertAccountParams) error
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	InsertBudget(ctx context.Context, arg InsertBudgetParams) error
	InsertDomainEvent(ctx context.Context, arg InsertDomainEventParams) error
	InsertOutboxEntry(ctx context.Context, arg InsertOutboxEntryParams) error
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) error
	MarkDomainEventProcessed(ctx context.Context, id uuid.UUID) error
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxProcessed(ctx context.Context, id uuid.UUID) error
	RevokeAllSessionsByUser(ctx context.Context, arg RevokeAllSessionsByUserParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error
}

var _ Querier = (*Queries)(nil)
