// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, created_at, last_activity_at, expires_at, revoked_at, user_agent, ip_address, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateSessionParams struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	CreatedAt      time.Time      `json:"created_at"`
	LastActivityAt time.Time      `json:"last_activity_at"`
	ExpiresAt      time.Time      `json:"expires_at"`
	RevokedAt      sql.NullTime   `json:"revoked_at"`
	UserAgent      sql.NullString `json:"user_agent"`
	IpAddress      pqtype.Inet    `json:"ip_address"`
	Status         SessionStatus  `json:"status"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.LastActivityAt,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.UserAgent,
		arg.IpAddress,
		arg.Status,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, created_at, last_activity_at, expires_at, revoked_at, user_agent, ip_address, status
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.Status,
	)
	return i, err
}

const revokeAllSessionsByUser = `-- name: RevokeAllSessionsByUser :exec
UPDATE sessions SET status = $1, revoked_at = $2 WHERE user_id = $3
`

type RevokeAllSessionsByUserParams struct {
	Status    SessionStatus `json:"status"`
	RevokedAt sql.NullTime  `json:"revoked_at"`
	UserID    uuid.UUID     `json:"user_id"`
}

func (q *Queries) RevokeAllSessionsByUser(ctx context.Context, arg RevokeAllSessionsByUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllSessionsByUser, arg.Status, arg.RevokedAt, arg.UserID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET status = $1, revoked_at = $2 WHERE id = $3
`

type RevokeSessionParams struct {
	Status    SessionStatus `json:"status"`
	RevokedAt sql.NullTime  `json:"revoked_at"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.Status, arg.RevokedAt, arg.ID)
	return err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions SET last_activity_at = $1 WHERE id = $2
`

type UpdateSessionActivityParams struct {
	LastActivityAt time.Time `json:"last_activity_at"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionActivity, arg.LastActivityAt, arg.ID)
	return err
}
