// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactional_outbox.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const fetchPendingOutbox = `-- name: FetchPendingOutbox :many
SELECT id, domain_event_id, event_type, payload, created_at, processing_status, retry_count
FROM transactional_outbox
WHERE processing_status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

type FetchPendingOutboxRow struct {
	ID               uuid.UUID        `json:"id"`
	DomainEventID    uuid.UUID        `json:"domain_event_id"`
	EventType        string           `json:"event_type"`
	Payload          json.RawMessage  `json:"payload"`
	CreatedAt        time.Time        `json:"created_at"`
	ProcessingStatus ProcessingStatus `json:"processing_status"`
	RetryCount       int32            `json:"retry_count"`
}

func (q *Queries) FetchPendingOutbox(ctx context.Context, limit int32) ([]FetchPendingOutboxRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPendingOutboxRow
	for rows.Next() {
		var i FetchPendingOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.DomainEventID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessingStatus,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementOutboxRetry = `-- name: IncrementOutboxRetry :exec
UPDATE transactional_outbox SET retry_count = COALESCE(retry_count,0)+1, last_retry_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementOutboxRetry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementOutboxRetry, id)
	return err
}

const insertOutboxEntry = `-- name: InsertOutboxEntry :exec
INSERT INTO transactional_outbox (id, domain_event_id, event_type, payload, created_at, processing_status, retry_count)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOutboxEntryParams struct {
	ID               uuid.UUID        `json:"id"`
	DomainEventID    uuid.UUID        `json:"domain_event_id"`
	EventType        string           `json:"event_type"`
	Payload          json.RawMessage  `json:"payload"`
	CreatedAt        time.Time        `json:"created_at"`
	ProcessingStatus ProcessingStatus `json:"processing_status"`
	RetryCount       int32            `json:"retry_count"`
}

func (q *Queries) InsertOutboxEntry(ctx context.Context, arg InsertOutboxEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxEntry,
		arg.ID,
		arg.DomainEventID,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
		arg.ProcessingStatus,
		arg.RetryCount,
	)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE transactional_outbox SET processing_status = 'failed', last_error = $2, processed_at = NOW() WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID        uuid.UUID      `json:"id"`
	LastError sql.NullString `json:"last_error"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxProcessed = `-- name: MarkOutboxProcessed :exec
UPDATE transactional_outbox SET processing_status = 'processed', processed_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOutboxProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOutboxProcessed, id)
	return err
}
