// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (id, account_id, amount, memo) VALUES ($1,$2,$3,$4)
`

type InsertTransactionParams struct {
	ID        uuid.UUID      `json:"id"`
	AccountID uuid.UUID      `json:"account_id"`
	Amount    string         `json:"amount"`
	Memo      sql.NullString `json:"memo"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertTransaction,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.Memo,
	)
	return err
}
