// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkMobileNumberExists = `-- name: CheckMobileNumberExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE mobile_number = $1)
`

func (q *Queries) CheckMobileNumberExists(ctx context.Context, mobileNumber string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkMobileNumberExists, mobileNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, date_of_birth, mobile_number, email, username, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, username, email, full_name, created_at
`

type CreateUserParams struct {
	FullName     string    `json:"full_name"`
	DateOfBirth  time.Time `json:"date_of_birth"`
	MobileNumber string    `json:"mobile_number"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
}

type CreateUserRow struct {
	UserID    uuid.UUID `json:"user_id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	FullName  string    `json:"full_name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FullName,
		arg.DateOfBirth,
		arg.MobileNumber,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, email, full_name, mobile_number, password_hash, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	UserID       uuid.UUID `json:"user_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	FullName     string    `json:"full_name"`
	MobileNumber string    `json:"mobile_number"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.MobileNumber,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, full_name, mobile_number, password_hash, created_at, updated_at
FROM users
WHERE user_id = $1
`

type GetUserByIDRow struct {
	UserID       uuid.UUID `json:"user_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	FullName     string    `json:"full_name"`
	MobileNumber string    `json:"mobile_number"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.MobileNumber,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByMobileNumber = `-- name: GetUserByMobileNumber :one
SELECT user_id, username, email, full_name, mobile_number, password_hash, created_at, updated_at
FROM users
WHERE mobile_number = $1
`

type GetUserByMobileNumberRow struct {
	UserID       uuid.UUID `json:"user_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	FullName     string    `json:"full_name"`
	MobileNumber string    `json:"mobile_number"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetUserByMobileNumber(ctx context.Context, mobileNumber string) (GetUserByMobileNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByMobileNumber, mobileNumber)
	var i GetUserByMobileNumberRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.MobileNumber,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, email, full_name, mobile_number, password_hash, created_at, updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	UserID       uuid.UUID `json:"user_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	FullName     string    `json:"full_name"`
	MobileNumber string    `json:"mobile_number"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.MobileNumber,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
